### PR TITLE
Add asciinema recordings

### PR DESCRIPTION
**Pull request by dgzlopes**
- [X] Decide between hosted or local
- [X] Record pod-video
- [X] Record node-video 

Some thoughts:
- Local = All lives in git, easier to edit
- Hosted = Looks better, works better, fewer files in git (js, CSS, cast)

Added the same video in hosted and local formats, to see the difference.

### CODE REVIEW

**Comment by seeker89** [comment]
This is looking great, do you have any blockers?

**Comment by dgzlopes** [comment]
Hey @seeker89, thanks for asking! 

Well, I have a small blocker... time :smile: 

I hope I can allocate some time this weekend to spawn a gcloud k8s cluster and record the node example.

Also, any thoughts on the local vs hosted thing?

**Comment by seeker89** [comment]
Sure thing :) I was just wondering if you were waiting for any fixes before finishing this PR.

I think that I'm leaning towards local, but I don't have strong feelings about it either way - it's an awesome thing to have, one way or another.

**Comment by dgzlopes** [comment]
I ended up picking the hosted solution. For one simple reason, if we use the local one the 'player' is too small while using our docs template...

I added the source files, in case we want to re-upload it or make changes or whatever :)

**Pull request merged**
