### PR TITLE
Use flake8 to find Python syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Signed-off-by: Chris Clauss <cclauss@bluewin.ch>

### CODE REVIEW

**Comment by seeker89** [comment]
Thanks for the PR, @cclauss !

Now, for me to be able to merge this in, I'll need you to update that commit with `Signed-Off-By` info in the commit message (that's what the DCO bot is unhappy about).

You can read more about this in the [contributing document](https://github.com/bloomberg/powerfulseal/blob/master/CONTRIBUTING.md), but it boils down to:
- either add `-s` when commiting from the command line,
- or add `Signed-Off-By: Your Name <your@email.com>` in the commit description in the Github UI.

Then I can merge it in, and fix the `flake8` problems. Thanks ! 👍

**Comment by seeker89** [comment]
Hi @cclauss - will you please sign off that commit, or start another PR with the commit signed off ?
I can't merge this in without it 😢

**Comment by taliaga** [comment]
Hi @seeker89, I may be wrong but I believe @cclauss is a bot :)

**Comment by cclauss** [comment]
No a bot!

**Comment by seeker89** [comment]
@cclauss now that we established you're not a bot, can we update this and merge this in ? 😄

**Comment by seeker89** [comment]
@cclauss I'll close this now, feel free to re-submit with the right `-s` flag on your commit.

Thanks !

**Pull request closed without merging**
