### PR TITLE
Policy-runner: wait between runs rather than between scenarios

### PR DESCRIPTION
**Pull request by dnascimento**
Currently the loop waits between scenarios instead of between runs as supposed

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Comment by dnascimento** [comment]
Des this make sense?

**Comment by seeker89** [comment]
That's a good catch. It's not backwards compatible, but we're about to release a new major version, so that's fine. If you could just update the unit test, I'm fine with merging this in.

Thanks! 👍

**Comment by dnascimento** [comment]
@seeker89  the tests are now fixed, it actually looks more consistent. Do you want to increment the version? Please squash on merge

**Comment by seeker89** [comment]
Yes, please bump up the version and I'll get this merged in. Thanks!

**Pull request merged**
