### PR TITLE
Add datadog metrics collector

### LINKED ISSUE #123: Add Google Cloud (GCP) Cloud Driver
Running k8s on top of GCP (with the managed GKE offering or with installer) is pretty common right now, so this might be a great addition. Anyone working on it? If not I would love to start working slowly on this and submit some PR.

### LINKED ISSUE #132: Enhancement: add Datadog /metrics support
> Datadog [[0](https://www.datadoghq.com/)] is a monitoring service for cloud-scale applications, providing monitoring of servers, databases, tools, and services, through a SaaS-based data analytics platform.

The idea is to add a Datadog metrics collector to have insights into the various measurables of Powerfulseal (similar to the Prometheus one). Adding a new metrics collector seems straightforward! So if this feature looks reasonable for the project, I would like to work on it and submit a PR when ready.

[0] https://www.datadoghq.com/

### PR DESCRIPTION
**Pull request by dgzlopes**
PR adding the Datadog metrics collector. This PR closes #132 .

Datadog collector based on DogStatsd. Includes tests for the collector, docs on Metrics.md, example dashboard and example image.

A new argument called `--datadog-collector` has been added too!

Signed-off-by: dgzlopes <danielgonzalezlopes@gmail.com>

### CODE REVIEW

**Comment by seeker89** [comment]
This looks great. I don't have access to datadog right now, but I'll try to get one to test it out.

Thanks @dgzlopes this looks like an awesome contribution.

**Comment by dgzlopes** [comment]
Take your time @seeker89!

Actually, I'm a little worried about the Datadog Import/Export functionality, as Table Widgets are missing... It might need some tweaking.

On the other hand, I built a script that generates metrics mock data (should work with all collectors). Right now is a little dirty, but if you think it could be useful for someone building a dashboard I can clean it and maybe submit it under a /scripts dir.

**Comment by seeker89** [comment]
Hey, just to update, I haven't forgotten about this PR, I just still don't have a datadog to test it against.

**Comment by seeker89** [comment]
OK, so I had a read through it, and it looks good. Could you please bump the minor version to 2.7.0 and LGTM ?

Thanks :)

**Comment by dgzlopes** [comment]
Thank you for taking some time to review the PR @seeker89 :)

Minor version bumped!

**Pull request merged**
