### PR TITLE
lazy load cache of netinterface objects to reduce azure api thrashing

### PR DESCRIPTION
**Pull request by whilke**
**Describe your changes**
For large node count azure AKS clusters the azure driver was taking a very long time (10s of minutes) to build the node inventory. Looks like for every group it would re-fetch network interface objects through the azure API for every node.

I added a simple lazy load cache of network interface objects based on resource name (nic resource).

**Testing performed**
Did development testing against our different AKS cluster sizes to validate no regressions and can now run.

### CODE REVIEW

**Comment by seeker89** [comment]
Hey @whilke thanks a lot for the contribution!

This is looking good. The DCO bot is unhappy - could you please make it happy be following [these intructions](https://github.com/bloomberg/powerfulseal/pull/211/checks?check_run_id=605648612)? I'll then be able to merge. Thanks!

**Comment by whilke** [comment]
@seeker89 done

**Comment by seeker89** [comment]
@whilke awesome, thanks! Could you update the branch so that I can merge? For some reason Github doesn't have the update button on this PR.

**Comment by whilke** [comment]
@seeker89 done

**Pull request merged**
