### PR TITLE
Chore - add more test coverage for aws_driver

### PR DESCRIPTION
**Pull request by clickthisnick**
Description:
Adding a couple tests around aws driver.
- Adds test to check that nodes can be created via public ip address
- Adds test to assert that no nodes are returned if fetching ec2 instances with an invalid ip address

Testing checklist:
- [x] Ran tests locally via tox

### CODE REVIEW

**Comment by clickthisnick** [comment]
The failing tests are also failing locally for me in master:
`test_prometheus_collector.py`
`tests/policy/test_label_runner.py`

**Comment by kz** [comment]
Hi @clickthisnick, I'm not maintaining this report but the failing tests relate to my commits. Do mind providing a few screenshots of the failing tests?

**Comment by seeker89** [comment]
It looks like the prometheus library introduced a backwards-incompatible change.
We should lock down the version or upgrade.

**Comment by seeker89** [comment]
Hey @clickthisnick sorry it took a while.

I've corrected two problems via https://github.com/bloomberg/powerfulseal/pull/78 and this is now ready to :shipit: 

Thanks for your contribution !

**Pull request merged**
