### PR TITLE
Add new logo for powerful seal

### PR DESCRIPTION
**Pull request by caniszczyk**
A new logo for our Powerfulseal friends!

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

Resolves https://github.com/bloomberg/powerfulseal/issues/60

### CODE REVIEW

**Comment by kpfleming** [comment]
We'll need to know the copyright holder's name for the logo artwork (LF or CNCF or whatever is correct), and a suitable license will need to be chosen for it as well since the Apache 2 license on the repo isn't really appropriate for artwork. CC-BY-SA or CC-BY would be fine, depending on what the copyright holder prefers for downstream users of the logo.

**Comment by caniszczyk** [comment]
We are OK with licensing under CC-BY as the logo creator.

**Comment by kpfleming** [comment]
Thanks. What should the copyright holder's name be?

**Comment by caniszczyk** [comment]
Linux Foundation

**Comment by kpfleming** [comment]
OK, then we can add a line to README.md like this:

PowerfulSeal logo Copyright 2018 The Linux Foundation, and distributed under the Creative Commons Attribution (CC-BY-4.0) [license](https://creativecommons.org/licenses/by/4.0/legalcode).

**Comment by seeker89** [comment]
Perfect ! Thanks so much, @caniszczyk and @kpfleming 👍

**Pull request merged**
